#!/bin/bash
#
# Validate Environment and Generate Report
# This script checks if all required services are configured
#

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     QA-FRAMEWORK Environment Validation Report            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}\n"

report_file="ENV_VALIDATION_REPORT_$(date +%Y%m%d_%H%M%S).md"

# Check environment variables
echo -e "${CYAN}Checking environment variables...${NC}\n"

missing=()
configured=()

[ -z "$DATABASE_URL" ] && missing+=("DATABASE_URL") || configured+=("DATABASE_URL")
[ -z "$REDIS_URL" ] && missing+=("REDIS_URL") || configured+=("REDIS_URL")
[ -z "$STRIPE_API_KEY" ] && missing+=("STRIPE_API_KEY") || configured+=("STRIPE_API_KEY")
[ -z "$STRIPE_WEBHOOK_SECRET" ] && missing+=("STRIPE_WEBHOOK_SECRET") || configured+=("STRIPE_WEBHOOK_SECRET")
[ -z "$JWT_SECRET_KEY" ] && missing+=("JWT_SECRET_KEY") || configured+=("JWT_SECRET_KEY")

# Show configured
if [ ${#configured[@]} -gt 0 ]; then
    echo -e "${GREEN}✓ Configured:${NC}"
    for var in "${configured[@]}"; do
        echo -e "  ${GREEN}✓${NC} $var"
    done
fi

# Show missing
if [ ${#missing[@]} -gt 0 ]; then
    echo -e "\n${RED}✗ Missing:${NC}"
    for var in "${missing[@]}"; do
        echo -e "  ${RED}✗${NC} $var"
    done
fi

# Generate report
cat > "$report_file" << REPORT_EOF
# Environment Validation Report

**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Status:** $([ ${#missing[@]} -eq 0 ] && echo "✅ READY" || echo "⚠️ NEEDS CONFIGURATION")

## Configured Variables (${#configured[@]})

$([ ${#configured[@]} -gt 0 ] && for var in "${configured[@]}"; do echo "- ✅ $var"; done || echo "None")

## Missing Variables (${#missing[@]})

$([ ${#missing[@]} -gt 0 ] && for var in "${missing[@]}"; do echo "- ❌ $var"; done || echo "None")

## Next Steps

$([ ${#missing[@]} -gt 0 ] && echo "### Required Actions:

1. **Configure PostgreSQL** (15 min)
   - Go to: https://railway.app
   - Add service → Database → PostgreSQL
   - Copy DATABASE_URL to environment variables

2. **Configure Redis** (10 min)
   - Add service → Database → Redis
   - Copy REDIS_URL to environment variables

3. **Configure Stripe** (10 min)
   - Go to: https://dashboard.stripe.com
   - Get API keys (test mode)
   - Set STRIPE_API_KEY and STRIPE_WEBHOOK_SECRET

**Total time:** 35-50 minutes

After configuration, run:
\`\`\`bash
./scripts/auto_setup_after_config.sh
\`\`\`" || echo "### Ready for Setup!

All environment variables are configured. Run:

\`\`\`bash
./scripts/auto_setup_after_config.sh
\`\`\`

This will:
- Validate all connections
- Run database migrations
- Create admin user
- Setup Stripe webhooks
- Run smoke tests")

---

Generated by validate_and_report.sh
REPORT_EOF

echo -e "\n${GREEN}Report generated: $report_file${NC}"

# Exit with appropriate code
[ ${#missing[@]} -eq 0 ] && exit 0 || exit 1
